Feature: Metrics Update
open-format/metrics-subgraph pull request #3
Opened 2024-05-21 12:42 UTC by refugene

- Remove Constellation related code and renamed Star to App
- Rename `Stats` to `Stat` in the loadOrCreate helper
- Add Arbitrum Sepolia network
- Populate Transaction Entity from RewardFacet

2024-05-23 16:35 UTC, george-openformat requested changes
looks good to me! 

just one thing with the AppFactory.json

2024-05-23 16:35 UTC, george-openformat commented on abis/AppFactory.json
only need the "abi" part of this file. lines 2-159

2024-05-27 14:22 UTC, refugene commented on abis/AppFactory.json
Thanks @george-openformat I have removed the rest of the file . I kept lines 2-259

2024-05-28 15:16 UTC, george-openformat approved these changes

2024-05-30 04:44 UTC, nup9151f approved these changes

2024-05-30 06:24 UTC, george-openformat commented
Hey @tinypell3ts we are unable to merge this as it has "code owner review required"

2024-06-17 14:48 UTC, tinypell3ts approved these changes

2024-06-17 14:50 UTC, merged